services:
  - type: web
    name: backend
    env: docker
    plan: free
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://<deine-datenbank>.render.com:5432/<db>
      - key: DB_USER
        value: <user>
      - key: DB_PASSWORD
        value: <pass>
